### ISSUE TITLE
Cannot open or preview attached files

### ISSUE THREAD

**Issue by bajlek** [globaleaks/globaleaks-whistleblowing-software#4394]
### What version of GlobaLeaks are you using?

5.0.46 standart update via apt

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

All

### Describe the issue

Hi, I cannot open downloaded files that were attached in form. I fill form and add JPG PNG and PDF files, but none of them are working in version 5.0.46. Preview also is not working. My system is Ubuntu 22.04.5 LTS. In older version from 2 weeks ago works everything fine. Is this my problem of filesystem, or this is an bug of this version. How can I downgrade version 5.0.44 or 5.0.45 ? Thank you

### Proposed solution

Downgrade?

**Comment by bajlek** [comment]
So I did downgrade apt install globaleaks=5.0.44 and fill again form in this version and still no PDF and image files work. It looks like that the header of file is corrupted?

Images
![Image](https://github.com/user-attachments/assets/408b4764-1093-451a-acc1-0a072adf6799)

PDF files
![Image](https://github.com/user-attachments/assets/4fed37c4-493c-4698-85a6-5e68ef2413fc)

Files
![Image](https://github.com/user-attachments/assets/9e3b592d-6fb7-474a-becc-ad9ec24dcc0e)

Files from 4 Feb 2025 till now are not working, files before are just fine.

**Comment by bajlek** [comment]
Solved with downgrade to version 5.0.42. In 5.0.44 in change log is
`Fix bug visualization of files uploaded by recipients introduced in 5.0.19`
So I decide that this can be a problem and that is why I downgrade to 5.0.42, now it is working. Can you fix that in release 5.0.47

All files uploaded in versions 5.0.44 and 5.0.46 is corrupted

**Comment by evilaliv3** [comment]
Hello @bajlek 

I confirm, we had a defect in releases 5.0.44-5.0.46. it manifestes only when multiple recipients are present.

We are issuing a fix for release 5.0.47.

Corrupted files unfortunately wll continue to not work.

**Comment by bajlek** [comment]
> Hello [@bajlek](https://github.com/bajlek)
> 
> I confirm, we had a defect in releases 5.0.44-5.0.46. it manifestes only when multiple recipients are present.
> 
> We are issuing a fix for release 5.0.47.
> 
> Corrupted files unfortunately wll continue to not work.

Thank you for this information. I will check that in 5.0.47

**Comment by evilaliv3** [comment]
Thank you @bajlek , the issue is now solved in release 5.0.48

**Comment by bajlek** [comment]
I just update to 5.0.48 and the problem is still there but only for some file types. For example PDF files, some files are working some  is corrupted, the same files which I upload as a test is working in 5.0.42 what do you need for debugging?
